#pragma once

#ifndef __MainWnd__
#define __MainWnd__

/**
@file
Subclass of IMainWnd, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

#include "Codepage.h"

//// end generated include

/** Implementing IMainWnd */
class xMainWnd : public ui::IMainWnd {
public:
	using this_t = xMainWnd;
	using base_t = ui::IMainWnd;

protected:
	//std::unique_ptr<wxComboBox> m_cmbEncoding;

public:
	/** Constructor */
	xMainWnd(wxWindow* parent);
	~xMainWnd() {
		//m_cmbEncoding.release();
	}

protected:
	std::filesystem::path m_folderCurrent;
	enum class eLST_COL : int { filename, encoding, size, comments };
	struct FILTER {
		std::wstring filters, filtersExclude, filtersFolder, filtersFolderExclude;
	};
	bool AnalyzePath(wxTreeListCtrl& lst, wxTreeListItem const& parent, std::filesystem::path const& path, FILTER const& filter);
	
	void SaveCurrentFolderPath(wxString const& strFolder);
	std::filesystem::path GetSelectedFilePath(wxTreeListItem item = {});

	template <typename tchar>
	std::basic_string<tchar> ReadFileAs(std::filesystem::path const& path, std::error_code& ec) {
		ec.clear();
		auto size = std::filesystem::file_size(path, ec);
		if (ec) {
			auto w = ec.message();
			return {};
		}
		std::basic_string<tchar> str;
		str.reserve(size/sizeof(tchar)+1);

		gtl::xIFArchive ar(path);
		auto bom = ar.ReadCodepageBOM(gtl::eCODEPAGE::DEFAULT);
		switch (bom) {
		case gtl::eCODEPAGE::UTF8:
		case gtl::eCODEPAGE::UTF16LE:
		case gtl::eCODEPAGE::UTF16BE:
		case gtl::eCODEPAGE::UTF32LE:
		case gtl::eCODEPAGE::UTF32BE:
			while (auto r = ar.ReadLine<tchar>('\n', false)) {
				str += *r;
				str += '\n';
			}
			break;
		default:
			{
				std::string s;
				s.resize(size);
				ar.Read<char>(s.data(), s.size());
				auto codepage = gtl::DetectCodepage(std::string_view(s));
				m_cmbEncoding->SetValue(codepage);
				// using ICU, convert string to wstring
				gtl::Ticonv<tchar, char> conv(nullptr, codepage.c_str());
				if (auto r = conv.Convert(s)) {
					str = *r;
					if (codepage.contains("JIS")) {
						using string_t = std::basic_string<tchar>;
						static std::pair<string_t, string_t> const pairs[]{
							{gtl::ToUTFString<tchar>(u8"‾"sv), gtl::ToUTFString<tchar>(u8"~"sv)},
							{gtl::ToUTFString<tchar>(u8"¥"sv), gtl::ToUTFString<tchar>(u8"\\"sv)} };
						for (auto& p : pairs) {
							for (auto pos = str.find(p.first); pos != str.npos; pos = str.find(p.first, pos + p.second.size())) {
								str.replace(pos, p.first.size(), p.second);
							}
						}
					}
				}
			}
			break;
		}
		return str;
	}

	bool ConvertFileEncoding(std::filesystem::path const& path, int codepage, bool bWriteBOM, bool bBackup, bool bPreserveTimestamps);
	
public:
	virtual void OnButtonClick_Analyze( wxCommandEvent& event ) override;
	virtual void OnButtonClick_Convert( wxCommandEvent& event ) override;

	virtual void OnButtonClick_Browse( wxCommandEvent& event ) override;

	virtual void OnTreelistSelectionChanged_Lst( wxTreeListEvent& event ) override;

	virtual void OnCombobox_Encoding( wxCommandEvent& event ) override;
	virtual void OnButtonClick_ConvertSelectedFile( wxCommandEvent& event ) override;
};

#endif // __MainWnd__
