#pragma once

#ifndef __MainWnd__
#define __MainWnd__

/**
@file
Subclass of IMainWnd, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

#include "Codepage.h"

//// end generated include

/** Implementing IMainWnd */
class xMainWnd : public ui::IMainWnd {
public:
	using this_t = xMainWnd;
	using base_t = ui::IMainWnd;

protected:
	//std::unique_ptr<wxComboBox> m_cmbEncoding;

public:
	/** Constructor */
	xMainWnd(wxWindow* parent);
	~xMainWnd() {
		//m_cmbEncoding.release();
	}

protected:
	gtl::xCodepageDetector m_codepage_detector;
	std::filesystem::path m_folderCurrent;
	std::optional<std::jthread> m_threadConverter;

	wxTreeListItems GetSelectedItems(bool bAllIfNone = false);

	enum class eLST_COL : int { filename, encoding, size, comments };
	struct FILTER {
		std::wstring filters, filtersExclude, filtersFolder, filtersFolderExclude;
	};
	bool AnalyzePath(wxTreeListCtrl& lst, wxTreeListItem const& parent, std::filesystem::path const& path, FILTER const& filter);
	
	void SaveCurrentFolderPath(std::filesystem::path const& strFolder);
	std::filesystem::path GetSelectedFilePath(wxTreeListItem item = {});

	bool ConvertFileEncoding(std::filesystem::path const& path, std::string const& codepage_source, int codepage_target, bool bWriteBOM, bool bBackup, bool bPreserveTimestamps);

public:
	virtual void OnButtonClick_Analyze( wxCommandEvent& event ) override;
	virtual void OnButtonClick_Convert( wxCommandEvent& event ) override;

	virtual void OnDirChanged_Browser( wxFileDirPickerEvent& event ) override{};
	virtual void OnButtonClick_Browse( wxCommandEvent& event ) override;

	virtual void OnTreelistSelectionChanged_Lst( wxTreeListEvent& event ) override;

	void OpenFileWith(std::wstring const& cmd);
	virtual void OnButtonClick_OpenWith1( wxCommandEvent& event ) override;
	virtual void OnButtonClick_OpenWith2( wxCommandEvent& event ) override;
	virtual void OnButtonClick_OpenWith3( wxCommandEvent& event ) override;

	virtual void OnCombobox_EncodingSource( wxCommandEvent& event ) override;
	virtual void OnButtonClick_ConvertSelectedFile( wxCommandEvent& event ) override;
};

#endif // __MainWnd__
