#pragma once

#ifndef __MainWnd__
#define __MainWnd__

/**
@file
Subclass of IMainWnd, which is generated by wxFormBuilder.
*/

#include "wxUI.h"

//// end generated include

/** Implementing IMainWnd */
class xMainWnd : public ui::IMainWnd {
public:
	using this_t = xMainWnd;
	using base_t = ui::IMainWnd;

public:
	/** Constructor */
	xMainWnd(wxWindow* parent);
//// end generated class members

public:
	virtual void OnButtonClick_Check( wxCommandEvent& event ) override;
	virtual void OnButtonClick_Convert( wxCommandEvent& event ) override;

	virtual void OnButtonClick_Browse( wxCommandEvent& event ) override;
};

#endif // __MainWnd__
